### ISSUE TITLE
Question about client reconnect and queued messages on the broker

### ISSUE THREAD

**Issue by mpe85** [hivemq/hivemq-mqtt-client#254]
I need some advice for this problem:

- A client is connected to the broker and the connection gets lost (e.g. due to a crash of the client)
- The session is persisted on the broker (session does not expire)
- In the meantime some messages are published to topics which that client had subscribed to. The broker queues those messages because the client is currently offline.
- The client reconnects (cleanSession=false) to the broker. The broker immediately sends the outstanding messages to the client.
- After the connection is established the client immediately subscribes to the topic on which the messages mentioned above are published to. But there is of cause a short time period between establishment of the connection and sending the subscriptions. In this period of time there are already some queued messages from the broker coming in. The HiveMQ MQTT client discards these messages because there are no subscriptions registered yet on that topic. This warning is raised:

WARN com.hivemq.client.internal.mqtt.handler.publish.incoming.MqttIncomingPublishService - No publish flow registered for MqttStatefulPublish{...}

I can see no possibility to not lose those messages. I would need some functionality to establish the connection and registerning the topic subscription on client side at the same time, but I found no way of doing this.

I'm using version 1.0 of the client library and HiveMQ broker 4.0.2. Protocol version is MQTT 5.

Do you have any advice how to handle this situation?

**Comment by SgtSilvio** [comment]
There are 2 options:
- The client application is still running, just the connection gets lost:
As long as the session is not expired, your callbacks (Async) or flows (Rx) will stay registered also when the client is disconnected. So if you reconnect, the messages will still be delivered to your callbacks/flows.
- The client application is restarted and a completely new client is created:
You have to call the `publishes(ALL)` method before the `connect` method. All messages (including the immediately received messages) will be delivered to this callback/flow.
Alternatively you can call `publishes(REMAINING)` before `connect` and then subscribe normally. All messages that are received in the time windows between establishing the connection and subscribing are then delivered to this callback/flow.

**Comment by mpe85** [comment]
Thanks for the help!

**Comment by SgtSilvio** [comment]
I am glad it helped.
I close this issue. If you have further questions feel free to open a new issue.

**Comment by patrickdmw** [comment]
Wow this is very much not intuitive.
Having to call PUBLISHES on a SUBSCRIBER client BEFORE calling connect, in order to not lose messages, especially given that `cleanStart(false)` is an option of the `Mqtt5ConnectBuilder` is not something I would have thought about before finding this bug request.
This should at least be part of one of the examples,
ideally be integrated into the `Mqtt5ConnectBuilder` and `Mqtt3ConnectBuilder` builder,
or even change the `cleanStart` / `cleanSession` methodes to something like `withPersistentSession(REMAINING, handler)` and `withCleanSession()` respectively, so users can not miss the option when trying to implement resilient applications using the hivemq client.
