### ISSUE TITLE
Client creates a non-daemon Thread that stops the application from closing

### ISSUE THREAD

**Issue by JulianFeinauer** [hivemq/hivemq-mqtt-client#414]
## Expected behavior
After `client.disconnect()` no non-daemon Threads should be alive.

## Actual behavior
After `client.disconnect()` a non-daemon Threads is alive, thus the application does not exit.
The Thread that is still Running is:
<img width="478" alt="grafik" src="https://user-images.githubusercontent.com/17098762/80231913-5a627c00-8654-11ea-9750-49f9c7965ac6.png">

### Steps
* Create a Blocking Client (MQTT 3.3).
* Connect
* Do a request / reply with Subscribe, Send, Wait for response, Unsubscribe for 3 Times (with 2 times it does not occur)

### Reproducer code

```
client.connect();

for (int i = 0; i < 3; i++) {
            requestReply(client, correlationId -> String.format(CHECK_EXISTS, "org.pragmaticindustries", "device", correlationId), json -> {
                System.out.println(json);
            });
}

client.disconnect();

```
where the `requestReply` method is as follows
```
    private static void requestReply(Mqtt3BlockingClient client, Function<String, String> requestHandler, Consumer<JSONObject> responseHandler) throws InterruptedException {
        String correlationId = UUID.randomUUID().toString();

        client.subscribeWith()
            .topicFilter("ditto/replies/" + correlationId)
            .qos(MqttQos.AT_LEAST_ONCE)
            .send();

        client.publishWith()
            .topic("ditto/incoming")
            .payload(requestHandler.apply(correlationId).getBytes())
            .send();

        Mqtt3Publish msg = client.publishes(MqttGlobalPublishFilter.SUBSCRIBED)
            .receive();

        String s = new String(msg.getPayloadAsBytes());

        JSONObject json = new JSONObject(s);

        String responseId = json.getJSONObject("headers").getString("correlation-id");

        if (responseId.equals(correlationId)) {
            System.out.println("Got a valid response... ");
            responseHandler.accept(json);
        } else {
            System.out.println("Something bad happened...");
        }

        client.unsubscribeWith()
            .addTopicFilter("ditto/replies/" + correlationId)
            .send();
    }
```

Note: Request-Reply works and the output and behavior of the program is as expected
Note: If I change the for-loop above to `i < 2` it works as expected. So the Bug seems to be there only for 3 or more loops.

## Details
- Affected HiveMQ MQTT Client version(s): 1.2.0
- Used JVM version: AdoptJDK 1.8.0_252

**Comment by SgtSilvio** [comment]
Hi @JulianFeinauer 
Just took a quick look at your code:
1. There is a race condition, as you publish before calling `publishes`. This may cause that the client already received the message before you create the `Mqtt3Publishes` instance which again causes that receive does not return that message but waits for the next one.
1. Also, the `Mqtt3Publishes` must be closed when not needed anymore. If you are using a persistent session the `Mqtt3Publishes` instance will keep the client's event loops alive, when not closing them.

So regarding the first point you should change your code to something like (using try-with-resources as `Mqtt3Publishes` is `AutoCloseable`):
```java
try (Mqtt3Publishes publishes = client.publishes(MqttGlobalPublishFilter.SUBSCRIBED)) {

    client.publishWith()
            .topic("ditto/incoming")
            .payload(requestHandler.apply(correlationId).getBytes())
            .send();

    Mqtt3Publish msg = publishes.receive();
}
```

The reason why the event loop is still alive can be caused by both points.
1. When the first happens, your code might hang at the `receive` method waiting for another message. Do you see all 3 response outputs?
1. If you are using persistent session, not calling close or not using try-with-resources will cause the event loop to stay alive (as you might call receive at a later point of time). Are you using a persistent session?

Please comment if this helps you.

**Comment by JulianFeinauer** [comment]
Thank you for your fast help @SgtSilvio! Indeed it was me using the API wrong. It works after all the changes you suggest. Thank you!
