### ISSUE TITLE
Client Transport Configuration cannot be changed later

### ISSUE THREAD

**Issue by canique** [hivemq/hivemq-mqtt-client#432]
## Expected behavior
After creating an Mqtt5Client, it should be possible to switch SSL on/off by changing the transport configuration.

## Actual behavior
Extending the transport configuration has no effect.

### Reproducer code
```
//create mqtt5 client
client = MqttClient.builder()
                    .identifier(identifier)
                    .serverHost(address)
                    .serverPort(port)
                    .useMqttVersion5()
                    .build();

//change settings of mqtt5 client - has no effect!
client.getConfig().getTransportConfig().extend()
                .socketConnectTimeout(timeout, timeUnit)
                .sslWithDefaultConfig()
                .build();

//will show "off" - initial client did not change at all
Log.i(TAG, "SSL " + (client.getConfig().getTransportConfig().getSslConfig().isPresent()
                ? "on" : "off"));
```
## Details
- Affected HiveMQ MQTT Client version(s): 1.2.0
- Used JVM version: 8
- Used OS (name and version): Android 8
- Used MQTT version: 5
- Used MQTT broker (name and version): hivemq CE

**Comment by SgtSilvio** [comment]
Hi @canique 
You can not change the configuration of an MqttClient instance once it is created because it is immutable.
Calling the `MqttTransportConfig.extend` method just builds you a new `TransportConfig`, it does not change the client's configuration.
Instead, just build a new MqttClient instance with the new configuration.
