### ISSUE TITLE
MQTT 5 server without client takeover support and reconnect 

### ISSUE THREAD

**Issue by missourian55** [hivemq/hivemq-mqtt-client#497]
I am trying to simulate un-graceful disconnect and client takeover (in this case, the broker doesn't support it). Like to know how to re-establish the connection? I am not sure if this is a bug with HiveMQ client, but would like to disclose what I am testing and appreciate any recommendations.

### Steps

1. Start the application
2. Run it for few minutes. Publish a few messages to MQTT 5 broker
3. Close the laptop for few minutes and let it go to sleep
4. Open the laptop; application resumes and trying to post a new message to MQTT 5 broker.
5. Getting below error
```java
com.hivemq.client.mqtt.exceptions.MqttClientStateException: MQTT client is not connected.
```

### Reproducer code

```java

@ApplicationScoped
@JBossLog
public class PriceGenerator {

    private final Random random = new Random();

    @Inject
    Mqtt5BlockingClient mqtt5BlockingClient;

    @ConfigProperty(name = "mqtt.topic")
    String topic;

    @Scheduled(every = "45s")
    public void generateMessage() {
        
        // troubleshooting the problem
        if(!mqtt5BlockingClient.getState().isConnected()) {
            log.info("Mqtt in disconnect state. Re-establishing connection... ");
            try {
                destroy();
            } catch (Exception e) {
                e.printStackTrace(); //MqttClientStateException: MQTT client is not connected.
                log.error("disconnect failure");
            }
            try {
                mqtt5BlockingClient.connect();
            } catch (Exception e) {
                e.printStackTrace(); // MqttClientStateException: MQTT client is already connected or connecting.
                log.error("connect failure");
            }
        }

        mqtt5BlockingClient
            .publishWith()
            .topic(topic)
            .payload(String.valueOf(random.nextInt(100)).getBytes(UTF_8))
            .qos(AT_LEAST_ONCE)
            .messageExpiryInterval(120)
            .payloadFormatIndicator(Mqtt5PayloadFormatIndicator.UTF_8)
            .send();
    }

    @PostConstruct
    public void init() {
        log.info("Going to establish a subscription with a Mqtt broker...");
        mqtt5BlockingClient.toAsync()
            .subscribeWith()
            .topicFilter(topic)
            .qos(AT_LEAST_ONCE)
            .callback(publish -> {
                final Optional<ByteBuffer> correlationData = publish.getCorrelationData();
                log.infov("Received message: {0}  ->  {1}", publish.getTopic(), UTF_8.decode(publish.getPayload().get()));
            })
            .send();

    }

    @PreDestroy
    public void destroy() {
        mqtt5BlockingClient.disconnect();
        log.info("Disconnected the Mqtt client...");
    }

}

@Singleton
class AppConfig {

    @ConfigProperty(name = "mqtt.host")
    String host;

    @ConfigProperty(name = "mqtt.port")
    int port;

    @Singleton
    @Produces
    public Mqtt5BlockingClient mqtt5BlockingClient() {

        final Mqtt5BlockingClient client = MqttClient.builder()
            .useMqttVersion5()
            .serverHost(host)
            .serverPort(port)
            .identifier(UUID.randomUUID())
            .automaticReconnectWithDefaultConfig()
            .buildBlocking();

        client.connectWith()
            .simpleAuth()
            .username("test")
            .password(UTF_8.encode("test"))
            .applySimpleAuth()
            .sessionExpiryInterval(3600 * 24)
            .cleanStart(true) 
            .keepAlive(30)
            .send();

        return client;

    }

}

```

## Details
- Affected HiveMQ MQTT Client version(s): 1.2.2
- Used JVM version: Java 11
- Used OS (name and version): mac OS Intel
- Used MQTT version: MQTT 5
- Used MQTT broker (name and version): Solace 9.x

**Comment by SgtSilvio** [comment]
Hi @missourian55 
If you use `automaticReconnect`, then there is no reason to call `if (!isConnected) { disconnect; connect; }` yourself.
Currently, the client does not support disconnecting and reconnecting yourself when it will automatically reconnect (https://github.com/hivemq/hivemq-mqtt-client/issues/302).
So, everything should work and if you remove the `if (!isConnected) { disconnect; connect; }` code, then you should not get any exceptions logged.

**Comment by missourian55** [comment]
@SgtSilvio  Thank you!  I added  this `if (!isConnected) { disconnect; connect; }` after noticing that client is not automatically reconnecting. Does **MQTT server** have any special support for *client* `automaticReconnect`? In my case MQTT server is Solace

**Comment by SgtSilvio** [comment]
@missourian55 
sorry for the delayed response.
I don't know how Solace handles reconnects/client takeovers and so on.
To see if the server rejects reconnect attempts, please add a ConnectedListener and DisconnectedListener which log all connect attempts and failures:
```
MqttClient.builder()
            ...
            .automaticReconnectWithDefaultConfig()
            .addConnectedListener(context -> log.info("connected"))
            .addDisconnectedListener(context -> log.info("disconnected by {}, cause {}", context.getSource(), context.getCause()))
            ...
```

**Comment by HiveMQSupport** [comment]
Tune in to our upcoming webinars –– What's New in HiveMQ 4.7 & Testing MQTT in the Cloud Using MQTT.fx®

Dear hivemq/hivemq-mqtt-client,

It’s our pleasure to invite you to two of our upcoming webinars this month:

- What's New in HiveMQ: Inside the Upcoming HiveMQ 4.7 Release (https://cJgkn04.na1.hubspotlinks.com/Btc/LX+113/cJgkn04/VWxRgj7FSsJFV35qB84TtPxhV_gMC14xc2lnN1RGL-15mVy7V3Zsc37CgJ0JW4Y_3bB755pWMW75rLCJ5L8HJWW9hnKYm4tSrxtN6ZDF1m220C-W3MQZG63PWSSjVqW7H_3wRqGpW7NGVbX3GfT72W23Hv3S4W-v0FW7by10R67FHlTW1MPTWC2HsLryW5XZyP33T0ZNZW36VtJS2Gw_HrW4n56lK6ht7ghW6BMXwn9c4p2tW1RHlym32HsvRW8cfKRK4gdS7KVNqVqm8TD0W9W58QP442RQRRKW9kgv4b8WtfJdW6JgYZT6DQypQW7CnLcv7PMSVvN3f0k_FDY0c6VP_flX5QskhlVHZ1ZB43s-NpW806Vvc2PlY9YVYJJYN8g4t-4W7l5BNb7mN4FbW2b3t3H4T5c9yW3S8nMC2qfYhyW6F9tDl5nB0T8W2b9h0Z1ll5zYW4nDG_P6xtqhWVdhfQp2HMJPhN1CdX2K6z3l136141 )
- MQTT.fx® on HiveMQ Cloud: Testing MQTT in the Cloud is Now Easier Than Ever (https://cJgkn04.na1.hubspotlinks.com/Btc/LX+113/cJgkn04/VWxRgj7FSsJFV35qB84TtPxhV_gMC14xc2lnN1RGL-15mVy7V3Zsc37CgT-lW3-J0dC1xfjZzW5Nyns5388D2sW3J75_B2McKT7W5SKBBJ48_gpPW5-D7d-52q0GFW11W7tz1MQNW_W46Hs246jQtY5W6jGyk32-2J7SW1Bdccv2FqwF8V1FXvJ1HzTbVW4ghJMG2zCcFsW441sr22gBfRhW3FBHQ44CXWCcW6c0PRN39BDB0W2djFGx20TsXxW169YdB4zZXGrW65hLMQ33BPm6W9lGRsG2lxkwNW33ngVS7w8l5jW8kRcy44c28XfW8rP8dn67F7qlW3DgqXB8QM7lkW16Tmvq9fPTP9W6pl4Mq57RvPLW8yBHgd234w2wW90-0X554KZK3W7QZcwf8xW519W4w_xbN3PNT78W55_ZqH90t4cnW3zsV9C5SMP52N8BL4DNTYFqjW4szLJ25HvQfQW7zBbn611x0zQW3w37KD1m6Pdq3d-G1 )

Why You Should Attend:

>> What's New in HiveMQ: Inside the Upcoming HiveMQ 4.7 Release

In the webinar, Dominik Obermaier, CTO and co-founder of HiveMQ, and Georg Held, Engineering Manager at HiveMQ, will showcase the new features of HiveMQ 4.7 and discuss how customers can benefit from upgrading to the new release.

Date: Wednesday, September 15. 2021

Time: 5 pm CEST / 11 am ET / 8 am PT

Register Now
(https://cJgkn04.na1.hubspotlinks.com/Btc/LX+113/cJgkn04/VWxRgj7FSsJFV35qB84TtPxhV_gMC14xc2lnN1RGL-15mVy7V3Zsc37CgSbrW6FjlsK3BJPZ3W6H3b471yBZqqW4dx55r3v6XLHW612HzN10_c9fVgbnhM6L_6qQW51fKwC7RZPCsW24K3F48VtjR8W6y_vqD1NH9QRW4H7dqh8lY62ZW2Vny0R1S6FlMW7gn1Gy4hWYv4W1PTv525RYf5JW1_Mj6k7JPk2vW72wQJF19N1Z8W5C1jCD3BPWfyW6xXNFN21bwF7W7QGvq814nThSW5zn0q98tj8N4W23jwP15CN7l1N89S90jd2_QxW7VjgMj9bGt9kW5cQTXh51l3HtW4TMZB11GS8kzW7_fj8H1w89glW4BJcqb968pKYW2k7lnn42F_59W1q1C4_7MMRplW1C8Xzq4Kcc8dW4NN40Q1T6lRNW8000V21DTyZ2W8bJdHp5M0SCWW38XKj18gFC1zW6Bf7GX36b-WCW8bC5xt7GVD8X3jd51 )

>> MQTT.fx® on HiveMQ Cloud: Testing MQTT in the Cloud is Now Easier Than Ever

In the webinar, Magi Erber, Product Manager at HiveMQ, will show you how simple it is to set up HiveMQ Cloud, on AWS or Azure, and increase the number of MQTT connections according to the demands of your IoT use case. Further in the session, Jens Deters, Founder and CEO of Softblade, and Nikolas Blättermann, COO of Softblade, together will show how easy it is to test, simulate and debug your MQTT client connections as you scale your IoT project with the new MQTT.fx® for HiveMQ Cloud edition.

Date: Wednesday, September 29. 2021

Time: 5 pm CEST / 11 am ET / 8 am PT

Register Now
(https://cJgkn04.na1.hubspotlinks.com/Btc/LX+113/cJgkn04/VWxRgj7FSsJFV35qB84TtPxhV_gMC14xc2lnN1RGL-15mVy7V3Zsc37CgFzHW330m-l8KPSnrW35WRH04c-CrXN6qFb8JG335LW4JML8q8LqdVqW4nS0Fm4vPmX3W429z6q2nBGh-N2Kw18WdfxTtV8hyx54vF6cWN8MSpSVvLygkVglr983GW321N4599zgsBNnGW6st8fw5kRwpBW8JDj5z5xn7KPVv6w5M7vjCCSW80CS2J5QpSjnW6MVhKT8lVJNBW6n2Tb22w8zjvW8sLpDL5_5R2kW2zq-Wt4VHhzsVvSJp16xL6Y5W6SK1jL6RjgVsN6wh6ggmTpTrW8Jfwnc2frB-XW3v0Hwk1RNtmjV-dlxs2JK0RdW8qLQT27C547jW4gXM4R5J6GZCW7mKM187DCCf_W1NF7Ky1W_VFXW2F-_4d1mMB22W87R5tc80TBXXW3n-bGQ7C9-qgVY_JLw5j-5fQW8dLKXD2Y-t-v34PS1 )

We look forward to seeing you at both these sessions.

Regards,

Your HiveMQ Marketing Team

HiveMQ GmbH, Ergoldinger Straße 2a, Landshut, Germany

Manage preferences (https://hs-5867930.s.hubspotemail.net/hs/manage-preferences/unsubscribe?languagePreference=en&amp%3Bd=VnBf_W5pR2lTW2p76LK3-1rCSW45Qvcz1ZtkvRW3VZPb91ZlN0SW3K232F4p9KrgW4rCWZ43KbsvFW3R0gxZ41Tj6jW47szjy45RlhdW3P28X24hCPvhW43T2PJ8-zKhjW17f7hv5J9jXzW7F0CXb5l4cqXW5hQmFG5GMkQmV28RCj5fr5RwMGKd_P20N6TW4dSsLM6brh71VHScY8599d3b51cdBR1&amp%3Bv=3&_hsenc=p2ANqtz-90SDN9jLigfXkLSl_WQhyOiae7q-LLHVnIPkycdMkMW3zNNw3hMTdFZmC9NgwmHSyyV0RQVSoRjqbygkAJlqhxwEXcuaFwYd9tEKjr8D3ouxFe4MCR8ueB3YjKQYzw4oIPlIhOAe0sZ41uX4vdq6fpfePjBg&_hsmi=156959882 )

You are receiving this email because you filled out a form on our website

or visited us at our booth at a tradeshow.

Twitter (https://cJgkn04.na1.hubspotlinks.com/Btc/LX+113/cJgkn04/VWxRgj7FSsJFV35qB84TtPxhV_gMC14xc2lnN1RGL_w3pl3rV1-WJV7CgVB0N79gLPqY22ffW15XX2K2zlhm9N28-S_yqcq-nW32r1Ms5F1rNpW44bTGz3mxYXPW5gFHHF8-hJPzW9jFY353CMbl_W4kg8Mt8yvZlpW8SHtl43L8Bw1W1jbLry8NdvwXW6Df-SH4jLZSZW88pmpH2-8GkVN1vdpw04s37bW4rGXqk1kpGdGW8lfmgP64S7zhW50gN-44wtP5rW9b8WZJ7F1KTZW4ZQxyT4vJBxXW738frz7g0Cg9W3cd7BH6wsZh8W2DYs6z2_ljlNW14qf5k3M890YW1xh8g-2FPnVwW5lL7vH5mgXP6W4g6b-76Hbt_3W19Sw_1495CPtW2KhDVl4XJPDnW7lK2fW1wxkM_3fRJ1 )

LinkedIn (https://cJgkn04.na1.hubspotlinks.com/Btc/LX+113/cJgkn04/VWxRgj7FSsJFV35qB84TtPxhV_gMC14xc2lnN1RGL_Q3pl3LV1-WJV7CgWr1W483GS92KTQhsW8fKFPC2jwR-KN5v-jHHjgkXdW5HF-mK7gLLryW4hVbgw7b1n4xW3kXFwj1B8xD4N14DkW6Xw2c_W72F6zt23rl3TW3bNfts5wGwJqW51ctMk69FHFGW5Pg-Fj6Wql0SW29HpjY3f36dCW7t17Gn5F4FvfW4BgDqj3d_rLnW2fYMvR42H2TFVDFmwj6dpyDhW2H9WNH49R-qNW7DNttr76z2rmW42ngXk5PDFGyW2dl5qL7Syrt0W43f4FY5dMd6WW6D5Yw94f811rW75zdyG614JrhW2J1Q4c4BJB-PW2X0YQD16s4YHN8NDpRhpcm1zVbS0qL1wvg1nW4VBqY78TzpDyW3Cf3c876PvnbW665Dzw1pPJbc39_v1 )

Facebook (https://cJgkn04.na1.hubspotlinks.com/Btc/LX+113/cJgkn04/VWxRgj7FSsJFV35qB84TtPxhV_gMC14xc2lnN1RGL_w3pl3rV1-WJV7CgYCTW3yZn3560H3PZW4KBW6-8V8W7bW3n-zJt26LCC7MCbnf_QYNbSW4PnNLZ8jpqqWW59CrlW4SZZXcW2mFzR41wKF7PW7y2_WX66hCJPVSBdpf8nmJX9W8SCP1P22stn8W1jn6DY27zFvDW2jrz0S3Mc81xW1d_5r44tJNV9W8_Qv2f8H4tknW6GDGZx7-k3QqN9hFVtTvscnNVmX4Wj729sflN8yQXcnXdP49W7hDDRv7T789HW5bdg6Q4164F4W2T20531lLYjdW51LsSd3Q_BBhW74HcNZ3R47mfW964q8t7yM9YLW4XDR2C22rvpwW3PHgKv2Mtl4qW52w7Zt7TT4T1VXsYtR11Kl-F3j4M1 )

YouTube (https://cJgkn04.na1.hubspotlinks.com/Btc/LX+113/cJgkn04/VWxRgj7FSsJFV35qB84TtPxhV_gMC14xc2lnN1RGLZL5mVxSV3Zsc37CgFSmW4hTj9z7T8y8LW2tMJKk5hsPfkW9kJr5Y41Z05TW74Xz_M3ZnZpJW5L_fh23vg4CPW7kVYJY1r3NqDW8ZY-DP55f4YKVzKp_v4zGS22W1F-d7C25khhtW3r7F_D2yNQnJVlfnMj3vtqT6VSQRp48Z0X5KW4KjwKT61lQ6cVZw1SD2w1ycyW71ym993fBhqHW8T4lRC1DZymzW6mTcLZ3W9sDjW3gd-nl5Vv5mTW6y2yxW1BWknTW5J2SMp1q4nbYW70ld941RYh8PW2bQR9L6fz2rmW83FjNJ2jH21HW8ZGVKP8n2H61W2RbYJS1DjhPPW95Tt476fqzhCW7hm2wt6TfgTjW5JbPPF3YVH0ZW3-K7TB1XJfVlW2QNhNd3Fn6HVW3nkH-y5VLD0kW67QwhV5HTDXz3jKS1 )

**Comment by pglombardo** [comment]
Hi @missourian55 - it's been while since this issue has been updated.  I'm going to close it for now but if anything remains, feel free to re-open it again or file another issue.  Thanks for using the HiveMQ client!
