### ISSUE TITLE
Update To Android Studio 4, mqttclient problems java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by acaliaro** [hivemq/hivemq-mqtt-client#502]
## Expected behavior
I have updated to AS4. Now when I debug the application, I have 

java.lang.NoClassDefFoundError: com.hivemq.client.internal.mqtt.mqtt3.Mqtt3RxClientViewBuilder

With AS3.6 I have not this problem

## Details
- Affected HiveMQ MQTT Client version(s):     implementation 'com.hivemq:hivemq-mqtt-client:1.2.1'

- Used JVM version: 
- Used OS (name and version): Lollipop 5.1.1
- Used MQTT version: 
- Used MQTT broker (name and version):

**Comment by HiveMQSupport** [comment]
Tune in to our upcoming webinars –– What's New in HiveMQ 4.7 & Testing MQTT in the Cloud Using MQTT.fx®

Dear hivemq/hivemq-mqtt-client,

It’s our pleasure to invite you to two of our upcoming webinars this month:

- What's New in HiveMQ: Inside the Upcoming HiveMQ 4.7 Release (https://cJgkn04.na1.hubspotlinks.com/Btc/LX+113/cJgkn04/VW0fCt2GQl_vW5mcyPl2KYHtSW44_bnN4xc2hDN4Rsyfc5mVy7V3Zsc37CgZX7V98rLR7Xj66hVQ7GcW5MKJ1lF6mvbnWrQzRW4FgVt230KbwmW8xtdSR4GCrFQW3lzp1j4z0pptW8rj4px3DFPZgN1rM47R8wYbrW6n3_608dm9DFN7327tjDqMycW9bpBTF1Z6mtjW6cTfpT2-ljyRW7GkQF41kt3R7W2lkQSK8h50gfW3W9k1N96YTNjW3WV38G8Hy68YN2n_drCd8qBsW5TYl2P6SQclpVQ_T5L2xBbJsW2NRmxp5cD2xlW5Tkj6n6CqZ5hW3g2sJG8qjDf_W5RLTp19k8T2YMk_3lySNxnrW8_xHXm28YgH6W1H013P5GRn7hN3RX0Jfr2qXnN82jCbsllZyGW5jBps84CXLsMW6m_dGP9hm95VW56nYnm6YGB2CN6NtkRlRW8rdW6NnH3S1_KtrBW4z9t_s8Lvmkc3p3b1 )
- MQTT.fx® on HiveMQ Cloud: Testing MQTT in the Cloud is Now Easier Than Ever (https://cJgkn04.na1.hubspotlinks.com/Btc/LX+113/cJgkn04/VW0fCt2GQl_vW5mcyPl2KYHtSW44_bnN4xc2hDN4Rsyfc5mVy7V3Zsc37CgJfJW7_BYnr3JrP0DW1zldcN3WklWPW4dCRw38q-jnjW99Q3md2y8wY5W1clt3G14f5h3W3wWWyn2lmjw3N8ggnYQYY0zrW3ZX8cP580XyHW1lt5MH5zbGk_VFK3y71fVF1cW5xBScv44Gqp9W21Kqb24dMsnHW8rxwZ62-b5gmW60_C1h6Yf2xNW3ZWzp55hcX0TW3f6PYP7WQqZbW24xQVX8KhmDgW5YC7rZ6RmwctW1H1QMs3VqCkFW69tPcb6gC4K2W511B_95ylr9tN7kxRZQG2jDWW8S3hFh4jf0v5W924dF7351LDwN5Gb9Bkl9JB-W7z339C4ZJjTmVQ1XGf1MNH5fW7qQS4l5cgxGNW6L2-Nv917ztFVnYJ814HXV74W2LGz9L6rWhz7W6r2pgQ4VV8VlW3WgF8469mfrhW4g3wF_32kMlr388m1 )

Why You Should Attend:

>> What's New in HiveMQ: Inside the Upcoming HiveMQ 4.7 Release

In the webinar, Dominik Obermaier, CTO and co-founder of HiveMQ, and Georg Held, Engineering Manager at HiveMQ, will showcase the new features of HiveMQ 4.7 and discuss how customers can benefit from upgrading to the new release.

Date: Wednesday, September 15. 2021

Time: 5 pm CEST / 11 am ET / 8 am PT

Register Now
(https://cJgkn04.na1.hubspotlinks.com/Btc/LX+113/cJgkn04/VW0fCt2GQl_vW5mcyPl2KYHtSW44_bnN4xc2hDN4Rsyfc5mVy7V3Zsc37Cg-nGW5Kdcpx2TmWfrW6Wtz9z2mjKdJW7rWKFr7n2l4mW48bz2d3cDNR-W44PzMy26BTQdW2VcySS5vv6JDVp81ql2b-H-NW5zcY3N1S-2RPW3Hr54j3v6mWpW1k0_477zbFVYW41dHJ844gqDpW6Qrgkt1rHtr-N3Q0HQYx2kRmVRWpl_1pWd4RW6ktXn586HD6nV2hlDV6V3ZyWW4-GjMz23MNxpW414Ckp7wqVHqW1GL5kL198yrYW7Hj_Hd1WRmZ3W8Kp4Tk1p__tBW5R7Cg-8X22VtN2P-5xGhjdvwW7txd6Y1FxDqBW7nD9t68yg3fXW16JL2W4kKF8jW52F8MJ7hngJcW1Q6M2H4-LJZxW6bcjqK4t_RndW17R1L56hT_kXW256CXr5wbjKjW8cy15p7sj_FvW66BZp33T8yKJW41DJ0b3dQp2N32VY1 )

>> MQTT.fx® on HiveMQ Cloud: Testing MQTT in the Cloud is Now Easier Than Ever

In the webinar, Magi Erber, Product Manager at HiveMQ, will show you how simple it is to set up HiveMQ Cloud, on AWS or Azure, and increase the number of MQTT connections according to the demands of your IoT use case. Further in the session, Jens Deters, Founder and CEO of Softblade, and Nikolas Blättermann, COO of Softblade, together will show how easy it is to test, simulate and debug your MQTT client connections as you scale your IoT project with the new MQTT.fx® for HiveMQ Cloud edition.

Date: Wednesday, September 29. 2021

Time: 5 pm CEST / 11 am ET / 8 am PT

Register Now
(https://cJgkn04.na1.hubspotlinks.com/Btc/LX+113/cJgkn04/VW0fCt2GQl_vW5mcyPl2KYHtSW44_bnN4xc2hDN4Rsyfc5mVy7V3Zsc37CgQLtM-f0Kw1QbftW5bBPVQ5NJVkrN7CNjCWn93MhVcwfLB8ybs7ZW5-VFJK1bKjRzW4wdp4F9hrc00W3gRK-F58ZTWtW5SwyC76f6srRV2sjnk1GzH19W5zf2_-3Xj9hDVc9S987wK_B6VtvCDb103ckGW4ZbRW717bL68W6CD_vY1wjcshW7vgP538jLN7VW4tmmcW13H973W7xmchJ1q34kqW3JTTyc8G_NmYW51XQDz64PGDYW1HTLsK7FRD60W5xldT14yFcptW39Fkrv1cn3MBW1xl0wz8Rvrv_W1kQvR74v4S7KW4mYYF-6sDX7RW7Ww7J31_DNJdW47PzXM9k1G2tW1rdRJX8lQz5KW7DtW2N6V-m6tVbgQst4BdY-vW5VNdhw9cbtGxW8SYR7D6SgQ0LW11VJ1f5GRjZjW44SXC-2JQFMs3jxl1 )

We look forward to seeing you at both these sessions.

Regards,

Your HiveMQ Marketing Team

HiveMQ GmbH, Ergoldinger Straße 2a, Landshut, Germany

Manage preferences (https://hs-5867930.s.hubspotemail.net/hs/manage-preferences/unsubscribe?languagePreference=en&amp%3Bd=VnzSxg5pR2lTW2p76LK3-1rCSW45Qvcz1ZvfFMW4tt67L1_ptrMW47T5QP1Vy3ypW4ckXGH3KbsvFW3R0gx_1Svmc8W4rdYl145RlhdW3P28X24hCPvhW43T2PJ8-zKhjW15gBJz8PRBPfW6737K15q1jrCW5kb7xb6cp5cKVWnlSL630tr4MXk_7QbvWj2W9h4TFm2fbFXLV--Glg34Jt0n2fc2&amp%3Bv=3&_hsenc=p2ANqtz--Ze-cCVvyqMtI7Od5Gs_11q5ql5ZTYla4vXdHG3L1TZ1jtLoIjpNY3n0UhqEHIM6Zpvu5rb64gnkWlUgp1OBlpK6KC5bi7Dq8pJ72xdR_69dneUkxuGPYcRQm5u2nrCSg37mEzAepsfpbY2i8sUrRAspP8RQ&_hsmi=156959882 )

You are receiving this email because you filled out a form on our website

or visited us at our booth at a tradeshow.

Twitter (https://cJgkn04.na1.hubspotlinks.com/Btc/LX+113/cJgkn04/VW0fCt2GQl_vW5mcyPl2KYHtSW44_bnN4xc2hDN4RsygJ3pl3rV1-WJV7Cg-4mN6ZsQTG-_NGzW7Zn2sk76cLpyW4LqwFH5pQ1RCVSLPgY5vqPSYW1HzfBP12-4m_W3X0lBy2JFDmMVj1ntJ2h3SdvW6lzygv5d3PfLW5y4Y566qcJ40W1yry7V5kG9pqW4QWM9F9ld3j3W5_Rnlb3HNV8fVrnZ0h857zTDW3cNv4C1-vz0yW73xDqc8SP08RW7f88KS5XtHXTW91RJ5d230HZhVw3Ny34zyJLcN1ZFWnq70rLpW4SJ4Pc2QtPhMW8KBfzx5PxWQkN7S528HdfCvMW6_Q4ks7WVMNhW6Jb-mY2zC6XyW9bp25h2WF0PKW7d8C3c4lMrwVW6mnwZD3-PpVtW8hZ9fj2-qSbG32K81 )

LinkedIn (https://cJgkn04.na1.hubspotlinks.com/Btc/LX+113/cJgkn04/VW0fCt2GQl_vW5mcyPl2KYHtSW44_bnN4xc2hDN4Rsyg_3pl3LV1-WJV7CgTPwV_ZwQ34061l4W8xhzs14RlrH4N6llzTHqtdmPW2qbBJy36Q0QnW41skcX9dl_hwW788znw6gLgpDMXgtlMyb8RGVhkbbH1WTYfqW8nghHS3mZmvNV_DMQ05sbN8HW8n5FGB15fgMXV18qqM86RXcLW4cXv3c7Pp9f_W5qsXN88X2Ss2W99GNZm6YTq-ZW8XcklZ7fFglMN4Xc5MN8M7grN7v6jczJhlYrW4sc4DG7LK1VZN4BXGZbq2Vl9W1dnwtD3jmLKjMXwYW-VHk0JVCMFZx4XCFPRW5QqD_S291LSGN3D5f_DvFvTJW9h_cKt3_FcQgW7s80Sd552TykW5v6j6d1fQF6qVPk-qV5h4V7jW6SJmNF72Kxcg2jx1 )

Facebook (https://cJgkn04.na1.hubspotlinks.com/Btc/LX+113/cJgkn04/VW0fCt2GQl_vW5mcyPl2KYHtSW44_bnN4xc2hDN4RsygJ3pl3rV1-WJV7CgJLBW5N2qk74MPtMpW7gFW7_7V6B8ZW1g_0kQ3gL97QW7X4ybd4zrQcLN33WnYJCwKr-W67gSRC7yy6mKW8b74-X7GDhfbW61K5Xh6Nmy0lW98tZfB6WFClXW7tLBCd5M3jNgW1lMdKV2rPDs6W1bgzMS2m2mWKVJl0_87mZ26YW4b1mjW63s21BW9d3cC36PR8zXN827ygqYwrxjW9kXzxn46dPbcW6CLmfP7xDFJwW33ynWM8FHnGzW8MVxbN44VH37W85QsPK8KtPhqW4nl9LK1J03-GW3sC3Ks2HLLcPW2khtJQ8-G9g0W8cPgnm3mLF4yW1HY-Y53QhkGdW6dqTRX8qG-QjW4pYHs01v_4jW3jRN1 )

YouTube (https://cJgkn04.na1.hubspotlinks.com/Btc/LX+113/cJgkn04/VW0fCt2GQl_vW5mcyPl2KYHtSW44_bnN4xc2hDN4RsydX5mVxSV3Zsc37CgLM6VmC-Ky3YSC1CN5HdLLddrw1yW56WCcj5SM0Z3W28MG5-8l3B3ZW3xz11V5HCmdFW4Gpx-P8LPfV-W1NzQQF1LRRszW24rt6Y1TG3TtW7VT5M65VH3-qW1jb-HL5Yh4JgVXLv1q8Nd99_W3P2cD-83DkbbW1Fl0ws64QFtpN7S-1JG2dJVrW1_Yrj-87FQkVW69V4dm58yNb1W5T4zs67FsMz9Vctx3j5lj10cW4-9TvL4njx9NW11kxD_2mYzsnW92sbcD6G69TRW4MM8b-8dsvWqW4fRfLD3Ff0tQW4xZMRr2yhPRvW95F_6t6-JPMFN4V6WMwFghYpW5JhmZ_35pFZ2W3n1s7d37-l18W3zXqC08KDRv3N5550DmM9_BZW3JLfGc4GV425N6B7vQHpBSKq34TG1 )

**Comment by HiveMQSupport** [comment]
Tune in to our upcoming webinars –– What's New in HiveMQ 4.7 & Testing MQTT in the Cloud Using MQTT.fx®

Dear hivemq/hivemq-mqtt-client,

It’s our pleasure to invite you to two of our upcoming webinars this month:

- What's New in HiveMQ: Inside the Upcoming HiveMQ 4.7 Release (https://cJgkn04.na1.hubspotlinks.com/Btc/LX+113/cJgkn04/VVCnDR2QyJqfW5fBqSh4yQjQ8W5ZD33c4xc2l0N4xH9cL5mVy7V3Zsc37CgJ4FW8pTDsy7FYt9vN6TwmdP5QctfW7h34PP2RSTmNW28Q9lM5m8KyZW7YGW3Y7p3zwJW5-dDyg1SY2bdW6D32lg8ggvnpW1D_9bQ7__Y6xN6PX-VLR2qT0W2rcFt01Qg8sbW4cWhKg2_Sc4YW2xY8x36Bb4qsW4-bNzs4Y4_T0W173WzP1XlylcW9hhHkq5r-8WhW11Vhgp2ydzLkN4lJbt678D2VW3fRzFk36MW_NW2W8dY88j_jbfW9cpGrl7kxG61W1jK6NL37fd5vW8KW52z83wFCZW8RHn-b6G-mkvW5CJWk810n0QPN1bg0xmyXzGHN83_cfHzfn0XW4NlHr35mQQlrVKtk2z6bc-LFW1WZ3Pr1n8k7sW3dxvxd6cslC3N26BpqF3k6LxW1HlYzK96KZmgW1frQwX2-Kx9PVf9sD52hPGPs3dxM1 )
- MQTT.fx® on HiveMQ Cloud: Testing MQTT in the Cloud is Now Easier Than Ever (https://cJgkn04.na1.hubspotlinks.com/Btc/LX+113/cJgkn04/VVCnDR2QyJqfW5fBqSh4yQjQ8W5ZD33c4xc2l0N4xH9cL5mVy7V3Zsc37CgQ31N5QSyDqgcrHLW6ztD3P1K7LVXW1Z9WG26b0Z1YW8BsX1t6RNrZ6W2d5Hsw6rQ46ZW30mFcT5mkFcpW4Wd3Df7rB-wWW7j052b1XVC8lW1kfPsr3tFZyhW6p4Shx3zjJFnW4ClMYw2t6F8GN4k9xS_5lbCjW8NzSfh1ww3TvN4nSNhDrwVdBW5ZQDFL6XspnlW4b4sR62-gvtMW1-dFH68LQwTqW7tgSJg6ylzCnW3gTznK7S645CW7zkmZH3m5lWrW4NNJcT1mTYZmW5gwRnR1-SQBLVCdXYH5Zw88_W4ytl2Q30xKdlW4y6r_n3-sS4LW1VWN-_11gxtvW4gxyr74M0T2yW5SRl4W5fnC9_N2ZGVSGKFPQ5W30Hv8t7GN4N7W8gGknY8w1R3TW4JysP44bN6PJW89mHqH5_PYCwW98NcC_2c5LfV3kzd1 )

Why You Should Attend:

>> What's New in HiveMQ: Inside the Upcoming HiveMQ 4.7 Release

In the webinar, Dominik Obermaier, CTO and co-founder of HiveMQ, and Georg Held, Engineering Manager at HiveMQ, will showcase the new features of HiveMQ 4.7 and discuss how customers can benefit from upgrading to the new release.

Date: Wednesday, September 15. 2021

Time: 5 pm CEST / 11 am ET / 8 am PT

Register Now
(https://cJgkn04.na1.hubspotlinks.com/Btc/LX+113/cJgkn04/VVCnDR2QyJqfW5fBqSh4yQjQ8W5ZD33c4xc2l0N4xH9cL5mVy7V3Zsc37CgDGYW7DGdjZ50lDzBW2pFpWZ8KxRbTW4vFwzQ524XmfW6ZXHFm4xnmJJW85mGLL3Gv25WW6ycHBt16tB5xW6qQ11l3tnv3XW1gqXhd3Dmk__V6M9BM88xmMxW509dw56m18DfW77n6yn7zWJzSW7G8Csr49n2w9W5gHDNT5Xyp1TW6JxtgT3RfpM4W7H1V-f13tVpJW6tkT3K8JDSSsW3YXVmX967dyFW2fjnH77kRPJZN4xXGpbzRnv8TZ55J5jcQpxW3QPTDf8pWWmbW2MCJFY38y7TdW1vKRfH2KZjF3Vzt0cp3XXQd4W6NHwXC51CTQ-W5R36yj8WyFHYW1X1vHM7TLZYwW6wvC8S550Y4ZW7t7SJl8Xp0mhN4jVKDqd9jsMW4GTYnR19pkhYW256W6z16bTWMW6Z9-v432bQlgW2-jT1_7G75Xb3lhr1 )

>> MQTT.fx® on HiveMQ Cloud: Testing MQTT in the Cloud is Now Easier Than Ever

In the webinar, Magi Erber, Product Manager at HiveMQ, will show you how simple it is to set up HiveMQ Cloud, on AWS or Azure, and increase the number of MQTT connections according to the demands of your IoT use case. Further in the session, Jens Deters, Founder and CEO of Softblade, and Nikolas Blättermann, COO of Softblade, together will show how easy it is to test, simulate and debug your MQTT client connections as you scale your IoT project with the new MQTT.fx® for HiveMQ Cloud edition.

Date: Wednesday, September 29. 2021

Time: 5 pm CEST / 11 am ET / 8 am PT

Register Now
(https://cJgkn04.na1.hubspotlinks.com/Btc/LX+113/cJgkn04/VVCnDR2QyJqfW5fBqSh4yQjQ8W5ZD33c4xc2l0N4xH9cL5mVy7V3Zsc37CgZPcW2rdVDL5QBTfyW35nxbC2qY7c9W3HtBtT6n7CGqW1fCrGT5pK-HHW6Mcd_M8rTBK5W2V3Hrw6YcFyjN94cC3VTL9QSV27xwK7sDXN_W3PSkLw5FVt26W3dxjDz22J_WNW5KkmXV7rP6BmW7N-fDT8zD2P-W7pMBzm3rGm3RW1yg0J25FpjcDW1nsMTH8TxdbPW8QtLFk7-t-0bW4YzQHs6RPZ2fN3BHfPYVlsN4W1wTjFm45fkGNW79F81x8Y0M1HVfP9BG63v8ylW22q85w35Q08bW2Spjzm8HTXG1W2YMlNF4zNdT7W28Kmsh6bWj7kN4Z2SPdX-BTNVrQMVX4yl-qmW5_lV9h7yzcLQW1G1mzK1MWvPnW2jhjbS2RZLGMW52ndtQ1VR0pbVYvnx72X81F2N6kMWxZzqfTCV7VmV36gPgF334-V1 )

We look forward to seeing you at both these sessions.

Regards,

Your HiveMQ Marketing Team

HiveMQ GmbH, Ergoldinger Straße 2a, Landshut, Germany

Manage preferences (https://hs-5867930.s.hubspotemail.net/hs/manage-preferences/unsubscribe?languagePreference=en&amp%3Bd=VnzSxg5pR2lTW2p76LK3-1rCSW45Qvcz1ZsBpCW4mGR5Q3z7stFW4kLGYb4cj-XkW3_ss5p3KbsvFW3R0gx_1Svmc8W4rdYl145RlhdW3P28X24hCPvhW43T2PJ8-zKhjW15gBJz5_nFLfW7mYYJ56N1x3pW5J7r4C7nwq-LVXjhW3630tr4MXk_7QbvV87W3pd8Dk5vb0Z3W20WTQn6ynNpc3f0Z2&amp%3Bv=3&_hsenc=p2ANqtz-87vsC2IfOSdFfDJQI9I7kPfmq2b55pFdTTUICfQ0VpWw3-c_OwbDjeG3kdjbwXSS3BbosYgoVc1cptc3rtDCEEqXJ5nUD7Wcky5MDAOoNX9_Bi-o4iioBo-PesalXDnRkRotlVYeU16YNUxXnjUzVL6uNuMA&_hsmi=156959882 )

You are receiving this email because you filled out a form on our website

or visited us at our booth at a tradeshow.

Twitter (https://cJgkn04.na1.hubspotlinks.com/Btc/LX+113/cJgkn04/VVCnDR2QyJqfW5fBqSh4yQjQ8W5ZD33c4xc2l0N4xH9fc3pl3rV1-WJV7CgKYWW66kc5h4_jLtMVG9PfB47lRVqW2qDTTr7PLFzZVDr1cl5H6tFYN5kr8xP2DhdyV8V6nR3FKBfKW1kpJyt4Z3rhvN2sgZW_kB1SbW7X3PQZ6s44z_W8m8t5V66FF-_W13WCMp7_BRw4W4SytSZ3mDzW-N8zvfnlKPhm0W8CLPTP7-n1R9W2kDQ8p2nQ2lWW77jP5W4JGxR7W81Mt9m6t7zKLW3_r1k_1GpjdjW1S1zZS7FT3hfW5cJdF275l5PVN1KS6XDFyC00W8g4yDg32zqxHW62YmYQ60FN-_W929nrg7ZXfHxW5CK8x082whk5W1rB32J94XT-xN4nn7rqWJhLpW2Sxcd04Wzd_M2361 )

LinkedIn (https://cJgkn04.na1.hubspotlinks.com/Btc/LX+113/cJgkn04/VVCnDR2QyJqfW5fBqSh4yQjQ8W5ZD33c4xc2l0N4xH9fw3pl3LV1-WJV7CgTYwW4HC4qW7Z1CdPVZVzd_5gWjS0W4NCD1x6hX8nrW1yJRyf825BfcW7YcLHz295jfWVLsntT6Cz-JNN1X2J1GFBjmWN4S6gHhQZ08nW4M036x57jPmrW1tc0w95wcwt5W9csWJs1x9lxNW6-b7Pg7vxWVqF3F4wrVrc2dVYQG_H3RYQd-W6VbSBB4RPLz2W7CVTKf6xsFm_W5HyFd76jStK_W5s8qy373kq_LN3w791JjCXmVW3M4sxm2TfrSbVCvtmK816W_wW6Y2jHX2zhmrQW6k-Ktz3v8F7vW3FyCl61VXdYyW5hHZXj4S7fcSW3sYtvx7xpDqVW1ZTnkv2FQmt-W9bvJrz14mNTjW8LlkRK3PRxYmW7VKL2T4wTXHl3d4q1 )

Facebook (https://cJgkn04.na1.hubspotlinks.com/Btc/LX+113/cJgkn04/VVCnDR2QyJqfW5fBqSh4yQjQ8W5ZD33c4xc2l0N4xH9fc3pl3rV1-WJV7CgWZMW94q4cr8X9wlgVMfX3g6JsvpDW3JlT0t1ZcPlkW24vdYz6GfmXKVsMQ6J6dx0H3W7YfPdJ68_3zTW373hNZ3FGdZHW5q-9KR6Q5gJ9W7HbQrQ7m7dtLW9hwzTF7YsgdtVKCVkm3LQZrXDX13CdcXYxW8BtDtV93PsctVVvFrs4DdMFkW9f3_CT8BMMJDN9h92211WxcyVhGLzx5xV0V8W8285Q-54xQxdW45nmlw7JqZDTW8rpZR_6ZChHlW3W8SVF8FlTyFN3XHfnyWtl-yW11JRqf3NZl7rW35vL9Q5l6zDNW8TFYyv2bNHxdVpQt5q4PBrGrW3fxWtP9fQ3GWVZs-W66Y6_YT25p1 )

YouTube (https://cJgkn04.na1.hubspotlinks.com/Btc/LX+113/cJgkn04/VVCnDR2QyJqfW5fBqSh4yQjQ8W5ZD33c4xc2l0N4xH9cr5mVxSV3Zsc37CgMfKW57JVGt1vW0wbVdzcV98YpDq3W101WRy6Xnhv5W52b1RT1LCtl4W1ljT6G7W7pkPW2w9ggv3Lmp80W7y3Qtr3qjzsZW1nJgVN7c5JkRN9bWBc3BDb_SW8z-ftF7fFn4DW1fGVcK5grthKW4hCzCD3JxSpQW5NJdRD256WbWW564nYC8cdpX1W947vpf5gqkrqW7-MQQy24787-N55X8VVHMhJGW3f_sV356kQVcW40WnXY7fXW-FW8HDqn61xC0GNW1NlxYm1xWSSXW8zSkhD3v2ZnZW7wFZQf1Qv9zWW5N12NV1mGNQwW5PP2VG13ln58N2KPN6y-Zg-XW93KsyL4xt8FRW8sjZcw259VVRW2nHj6V1B38ksW4_JKJ_7m4wpRW1s46J_6hX1sCV-s_TQ6lRdGQ3gPB1 )

**Comment by SgtSilvio** [comment]
@acaliaro 
the new 0.4.0 release of android-retroffix (https://github.com/SgtSilvio/android-retrofix/releases/tag/v0.4.0) should work with Android Gradle Plugin 4.x and 7.x
Please comment if it works now.

**Comment by acaliaro** [comment]
it seems to work thanks @SgtSilvio
