### ISSUE TITLE
Upgrade netty-codec To 4.1.80.Final

### ISSUE THREAD

**Issue by UcanInfosec** [hivemq/hivemq-mqtt-client#542]
Upgrade the use of netty-code To 4.1.80.Final to remove 2 CVEs in the code

**Comment by SgtSilvio** [comment]
Hi @UcanInfosec 
As the hivemq-mqtt-client is a library, you can easily upgrade the dependency yourself.
If you build your project with Gradle, you could do the following:

```kotlin
dependencies {
    implementation("com.hivemq:hivemq-mqtt-client:1.3.0")
    implementation(platform("io.netty:netty-bom:4.1.80.Final"))
}
```

The next release of this library will of course upgrade the dependency by default so that no extra configuration is needed.
The next release will happen once we get to it which might actually happen soon.

**Comment by UcanInfosec** [comment]
@SgtSilvio Thanks. Although I can do this myself, I want it to get incorporated into the next release
