### ISSUE TITLE
Global configuration

### ISSUE THREAD

**Issue by SgtSilvio** [hivemq/hivemq-mqtt-client#57]
- [ ] Investigate global configuration options for MQTT Bee (e.g. timeouts between CONNECT and CONNACK, PINGREQ and PINGRESP)
- [ ] Concept for global configuration
- [ ] Implement global configuration

**Comment by christianhoff** [comment]
Global configuration options identified so far:

```
org.mqttbee.mqtt.handler
	.auth
	.connect
		.MqttConnectHandler
			CONNACK_TIMEOUT
	.disconnect
	.ping
		.MqttPingHandler
			PING_RESP_TIMEOUT
	.publish
		.MqttIncomingAckFlow
			REQUEST_BATCH_LIMIT
		.MqttPublishFlowables
			MAX_CONCURRENT_PUBLISH_FLOWABLES
	.ssl
		.KeystoreUtil
			KEYSTORE_TYPE
	.subscribe
		.MqttSubscriptionHandler
			MAX_SUB_PENDING
	.util
	.websocket
```

**Comment by christianhoff** [comment]
Approach 1: GlobalConfiguration object 
* use a GlobalConfiguration object that contains all global configuration data
* the configuration object can be passed over to the MqttClientBuilder
* the configuration object can also be initialized from a properties file
```
GlobalConfiguration config = GlobalConfiguration.builder().withConnackTimeout(10).build();
// Alternatively:
Properties configProperties = ...
GlobalConfiguration config = GlobalConfiguration.builder().fromProperties(configProperties).build();
// Alternatively:
String configPropertiesFileName = ...
GlobalConfiguration config = GlobalConfiguration.builder().fromPropertiesFile(configPropertiesFileName).build();

MqttClient.builder().usingGlobalConfiguration(config)...
```

Approach 2: expose global configuration settings on the  MqttClientBuilder API
* there is a dedicated method for each setting on the MqttClientBuilder API
* there could also be a method to initialize global config from properties

```
MqttClient.builder().withConnackTimeout(10)....
```

Approach 1 encapsulates all the global config in a separate object, so the individual settings would not be first class citizens of the MqttClientBuilder. That's why I would favor this approach since the normal case should be to go with the default values.

Which approach do you prefer? Also do we want to offer initialization of global settings from properties?

**Comment by david-katz** [comment]
Alternative 1 looks good to me!

Question for the JEE people: would you want to be able to configure this stuff via system properties?
