### ISSUE TITLE
QoS1 message with PUBACK with next message

### ISSUE THREAD

**Issue by KeithLaiKB** [hivemq/hivemq-mqtt-client#579]
In QoS1 in MQTT: 
there are 2 process in MQTT communication,
1.Publisher to Broker
2.Broker to Subscriber
In each process, when the server(publisher/broker) does not receive the PUBACK from the client(broker/subscriber) about **messageA**, will the server keep sending the second message **messageB** to the client? It seems like there is no reference mentioned that clearly.

**Comment by pglombardo** [comment]
Hi @KeithLaiKB,

If I understand your question correctly, [this section](https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901238) in the MQTT 5 specification should answer your question:

> When a Client reconnects with Clean Start set to 0 and a session is present, both the Client and Server MUST resend any unacknowledged PUBLISH packets (where QoS > 0) and PUBREL packets using their original Packet Identifiers. This is the only circumstance where a Client or Server is REQUIRED to resend messages. Clients and Servers MUST NOT resend messages at any other time 

The key point being: **Clients and Servers MUST NOT resend messages at any other time**

Since it's been quite some time since this issue was filed, I'll close this issue out.  But if this doesn't answer your question or if you have any other issues, let us know.  We'd be happy to help out!
